### ISSUE TITLE
UI questions

### ISSUE THREAD

**Issue by Xeverous** [mosra/magnum-extras#11]
https://doc.magnum.graphics/magnum/ui.html

Since the doc explicitly mentions it's not documented yet, I would like to ask some questions regarding the UI - I have an open-source project in mind and would like to use Magnum to make both a desktop and a web-based application (and to let you know - you have superior licensing compared to Qt).

- Do I need to use the Dear Imgui library?
  - If yes, how customizable it is? Can I change only colors or more (like geometry, size, alignment etc)
  - If not - is there any way to have custom widgets? Doc mentions there is a singal+slot system - as long as there is a sort of 2D canvas (similar to HTML 5 canvas API) I'm fine with it to draw my own widgets and implement my event handlers.

**Comment by mosra** [comment]
Hi!

yeah, the `Magnum::Ui` lib is pretty much on hold right now, and thus I don't recommend to use it. I still have a bunch design ideas that are worth pursuing I think, so I'm planning to revive it at some point in the future.

Yes, Dear ImGui is pretty much the go-to solution, and since the backend interface is very thin, anything you can do with "vanilla" ImGui you can do with the Magnum flavor as well (plus Magnum handles things like HiDPI for you). It's customizable to some extent (see e.g. the [Project Spotlight in latest release notes](https://blog.magnum.graphics/announcements/2020.06/#magnum-project-spotlight), most of these are made using ImGui) and it's possible to make custom widgets as well, but you have to consult ImGui docs/sources/projects for that. I'm not an ImGui user myself, so unfortunately can't help much on that front.

One thing that might be speaking *against* ImGui is that it requires the app to constantly redraw in order to process events properly. Which is fine for game-like use cases, but not so great for fullscreen apps that are mostly idle.

**Comment by Xeverous** [comment]
> I still have a bunch design ideas that are worth pursuing I think, so I'm planning to revive it at some point in the future

I encourage you then to look into [elements](https://github.com/cycfi/elements). It's a project I have contributed a lot to but ultimately resigned because the current vector graphics backend implementation (cairo) is 100% CPU based which is unacceptable (25% CPU usage for drawing while idle). The library optimizes this by not redrawing everything on every frame, but for a sufficiently complex application keeping track of elements that need to be refreshed is IMO too cumbersome. And if you do any more dynamic UIs, then you gonna redraw everything anyway. There is work undergoing to replace cairo with skia, but this one looks like a dependency-and-build-system nightmare. Plus there are some events that elements likely will not support (the author aims at very specific use cases).

Still, I think you should look how elements examples look - maybe you will come with something similar. I really got surprised with how clean modular API can be made to support arbitrary nesting of widgets. I'm only worried that this might end in a forest of shared pointers and inefficient callbacks in waterfall-hierarchical-event-passing (ECS or signal-slot is scaling much better when there is a lot of widgets and different event types).

> it's possible to make custom widgets as well, but you have to consult ImGui docs/sources/projects for that

I'm not used to immediate-mode UIs (could possibly adapt to it) but - how are events implemented? Are they completely on the Imgui side or does Magnum have own events (eg based on SDL)? Basically - how much can I get out of just Magnum?

> One thing that might be speaking against ImGui is that it requires the app to constantly redraw in order to process events properly.

I will likely need some more dynamic or at least frequent-but-significant changes on each frame, so redrawing everything on each frame doesn't bother me.

**Comment by mosra** [comment]
> elements

Cool, will definitely check it out for inspiration :) another source of inspiration is [how The Machinery does UI](https://ourmachinery.com/post/one-draw-call-ui/), but in their case the focus on pure C is hurting it a bit.

> how are events implemented?

The events are propagated from Magnum's Sdl2Application / GlfwApplication / ... classes and translated to what ImGui expects, that way the dependency on a particular toolkit is decoupled a bit. Check out the contents of [Context.hpp](https://github.com/mosra/magnum-integration/blob/master/src/Magnum/ImGuiIntegration/Context.hpp) for how it's actually done.

**Comment by Xeverous** [comment]
> another source of inspiration is how The Machinery does UI

I will look into this.

> The events are propagated from Magnum's Sdl2Application / GlfwApplication / ...

This is great news for me. Does Magnum have a sort of HTML5 canvas API (or something on this abstraction level)? I could then easily draw my own widgets.

**Comment by mosra** [comment]
No, but ImGui has something I think. Magnum is one level below.

**Comment by Xeverous** [comment]
https://github.com/ocornut/imgui/blob/a1597cff088a827e98688632f6523fae2b6513af/imgui.h#L2077-L2186

There is, pretty much exactly what I want

I looked at their examples and your running web demo - seems like I will be easily able to do everything I want.
