### ISSUE TITLE
How to install arch linux PKGBUILDs

### ISSUE THREAD

**Issue by KorigamiK** [mosra/magnum-extras#14]
I tried following the instructions from [Magnum's building docs](https://doc.magnum.graphics/magnum/building.html#building-packages-arch) and wanted to install the Emscripten wasm toolchain, however these pkgbuild's are not available in the AUR and installing them via makepkg gives me unresolved dependency errors.

```bash
Ξ package/archlinux → makepkg --nocheck -fp PKGBUILD-emscripten-webgl2
==> Making package: emscripten-magnum-extras dev.webgl2-1 (Tue 06 Dec 2022 07:15:34 PM IST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> emscripten-magnum=dev.webgl2
  -> emscripten-magnum-plugins=dev.webgl2
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

How do I go about installing those? What is the procedure?

**Comment by mosra** [comment]
Hi!

Each repository has a `package/archlinux` directory, and you just have to go in the dependency order. Thus:

1. clone [corrade](https://github.com/mosra/corrade), `cd package/archlinux`, make & install the `PKGBUILD-emscripten`
2. clone [magnum](https://github.com/mosra/magnum), `cd package/archlinux`, make & install the `PKGBUILD-emscripten-webgl2`
3. clone [magnum-plugins](https://github.com/mosra/magnum-plugins), `cd package/archlinux`, make & install the `PKGBUILD-emscripten-webgl2` 
    - there you may need additional dependencies such as Basis or FAAD2, solution is to either edit the PKGBUILD to not have them in `dependencies=()` (and also disable the corresponding `MAGNUM_WITH_*` option), or install them from PKGBUILDs in https://github.com/mosra/archlinux
4. and then finally clone and install this repo :)

I'm not putting Emscripten-specific PKGBUILDs into the AUR because Emscripten tends to be finicky and the PKGBUILDs break every now and then on various Emscripten versions, apart from that every Emscripten project usually sets its own compilation and optimization settings (threads or not, SIMD or not, etc...), which is hard to generalize.

**Comment by KorigamiK** [comment]
Oh, this makes sense. Seems like a lot of manual work is required. 

Has anyone tried to create a Docker image for Magnum Emscripten toolchain?

That would solve a lot of problems building and deploying for the web if it can be done in CI and development can be done using platform specific binaries :)

**Comment by mosra** [comment]
I'm not aware of any public and up-to-date Docker image, no, sorry.

The PKGBUILDs were originally made mainly for my own development workflow as I prefer to rely on system packages rather than containerized environments. Less overhead that way.

As an alternative to external dependencies you might want to go with CMake subprojects (with Magnum etc. as Git submodules, for example). That's nicely self-contained, but the disadvantage is that a full rebuild is ... really a full rebuild of *everything* :)

**Comment by KorigamiK** [comment]
I think I've understood most of the build steps, I tried to read the [docs](https://doc.magnum.graphics/magnum/platforms-html5.html#platforms-html5-events) pretty carefully. I'll try to compile the dependencies myself first.

I'll be closing this issue until I manage to mess up something.
